imports:
    - { resource: parameters.yml }
    - { resource: custom_parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AirSimSocialNetworkBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#            apply_to: "\.css"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# HTML compressor
html_compressor:
    enabled:  true
    jar:      "%kernel.root_dir%/Resources/java/htmlcompressor-1.5.3.jar"
    options:  {'--type': html}

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
                    defaults:
                        mappings:
                            AirSimCoreBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Avalanche Imagine
avalanche_imagine:
    filters:
        avatar:
            type:     thumbnail
            options:  { size: [117, 117], mode: outbound, quality: 100, format: jpg, cache_type: private }
        last_photo:
            type:     thumbnail
            options:  { size: [280, 215], mode: outbound, quality: 100, format: jpg, cache_type: private }
        users_photo:
            type:     thumbnail
            options:  { size: [84, 84], mode: outbound, quality: 100, format: jpg, cache_type: private }
        wall_rec_img:
            type:     thumbnail
            options:  { size: [128, 128], mode: outbound, quality: 100, format: jpg, cache_type: private }
# Services
services:
    kernel.listener.air_sim_exception_listener:
        class: AirSim\Bundle\CoreBundle\Services\AirSimExceptionListenerService
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

# Hearsay RequireJS
hearsay_require_js:
    require_js_src:  ./../../assets/js/plugins/require-js-2.1.15.js
    initialize_template: HearsayRequireJSBundle::initialize.html.twig
    # Folder with JavaScript modules
    base_url:  ../assets/js/themes
    # Folder for r.js optimizer
    base_dir: %kernel.root_dir%/../web/assets/js/optimized # Required
    # Paths for plugins
    paths :
        jquery:
            location: ./../../../assets/js/plugins/jquery-1.11.1
            external: true
        jquery.form:
            location: ./../../../assets/js/plugins/jquery-form
            external: true
        jquery.ddslick:
            location: ./../../../assets/js/plugins/jquery.ddslick
            external: true
        jquery.selectric:
            location: ./../../../assets/js/plugins/jquery.selectric
            external: true
        jquery.knob:
            location: ./../../../assets/js/plugins/jquery.knob
            external: true
        jquery.qtip:
            location: ./../../../assets/js/plugins/jquery.qtip
            external: true
        jquery.autosize:
            location: ./../../../assets/js/plugins/jquery.autosize
            external: true
        autobahn:
            location: ./../../../assets/js/plugins/autobahn-wamp1
            external: true
        when:
            location: ./../../../assets/js/plugins/when
            external: true
        requirejs.async:
            location: ./../../../assets/js/plugins/require-js-async-0.1.2
            external: true
        # Nokia Here map
        here:
            location: ./../../../assets/js/plugins/jHERE/jhere
            external: true
        here.markers:
            location: ./../../../assets/js/plugins/jHERE/extensions/markers
            external: true
        here.geocode:
            location: ./../../../assets/js/plugins/jHERE/extensions/geocode
            external: true
        # Formstone components
        formstone.scroller:
            location: ./../../../assets/js/plugins/formstone/components/scroller/jquery.fs.scroller
            external: true
    # Shim config (dependencies of plugins / modules, their exports )
    shim:
        jquery.selectric:
            deps: [jquery]
        jquery.autosize:
            deps: [jquery]
        here:
            deps: [jquery]
        here.markers:
            deps: [here]
        here.geocode:
            deps: [here]
    # Optimizer config, (for us r.js)
    optimizer:
        path: %kernel.root_dir%/../web/assets/plugins/r-2.1.15.js
        # For production hide every non optimized files for web folder
        hide_unoptimized_assets: true
        # Optimizer config (r.js https://github.com/jrburke/r.js/blob/master/build/example.build.js, for example)
        options:
            removeCombined: true
            name: main
            # lib uglify2 for optimization, included in r.js
            optimize: uglify2
            # uglify2 lib config
            uglify2:
                output:
                    beautify: false
                compress:
                    sequences: true
                    global_defs:
                        DEBUG: false
                warnings: true
                mangle: false