imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

monolog:
    handlers:
        main:
            type:   stream
#            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            path: "%logs_dev_dir%%logs_dev_all_channels_file%"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
#        firephp:
#            type:   firephp
#            level:  info
#        chromephp:
#            type:   chromephp
#            level:  info

assetic:
    use_controller: %use_assetic_controller%

#swiftmailer:
#    delivery_address: me@example.com

# Hearsay RequireJS
hearsay_require_js:
    require_js_src:  ./../../assets/js/plugins/require-js-2.1.15.js
    # Folder with JavaScript modules
    base_url:  ../assets/js/themes
