parameters:
#    air_sim_admin.example.class: AirSim\Bundle\AdminBundle\Example

services:
#    air_sim_admin.example:
#        class: %air_sim_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
