# ***** Accounts ***** #
air_sim_social_network_accounts:
    path:     /accounts/{action}
    defaults: { _controller: AirSimSocialNetworkBundle:Accounts:accounts }
# AJAX calls
air_sim_social_network_accounts_login:
    pattern:  /accounts_login_check
    defaults: { _controller: AirSimSocialNetworkBundle:Accounts:loginCheck }

# ***** User ***** #
air_sim_social_network_user:
    path:     /user/{username}
    defaults: { _controller: AirSimSocialNetworkBundle:User:user }
# AJAX calls
air_sim_social_network_user_get_photo_data:
    path:     /user_get_photo_data
    defaults: { _controller: AirSimSocialNetworkBundle:User:getPhotoData }
air_sim_social_network_user_add_wall_record:
    path:     /user_add_wall_record
    defaults: { _controller: AirSimSocialNetworkBundle:User:addWallRecord }
air_sim_social_network_user_upload_tmp_images:
    path:     /user_upload_tmp_images
    defaults: { _controller: AirSimSocialNetworkBundle:User:uploadTmpImages }
air_sim_social_network_user_delete_tmp_image:
    path:     /user_delete_tmp_image
    defaults: { _controller: AirSimSocialNetworkBundle:User:deleteTmpImage }
air_sim_social_network_user_like_dislike_wall_record:
    path:     /user_like_dislike_wall_record
    defaults: { _controller: AirSimSocialNetworkBundle:User:likeDislikeWallRecord }
air_sim_social_network_user_reply_to_wall_record:
    path:     /user_reply_to_wall_record
    defaults: { _controller: AirSimSocialNetworkBundle:User:replyToWallRecord }
air_sim_social_network_user_rate_photo:
    path:     /user_rate_photo
    defaults: { _controller: AirSimSocialNetworkBundle:User:ratePhoto }

# ***** Contacts ***** #
air_sim_social_network_contacts:
    path:     /contacts/{type}
    defaults: { _controller: AirSimSocialNetworkBundle:Contacts:contacts }
# AJAX calls
air_sim_social_network_contacts_search:
    path:     /contacts_search_contacts
    defaults: { _controller: AirSimSocialNetworkBundle:Contacts:searchContacts }
air_sim_social_network_contacts_add:
    path:     /contacts_add_contacts
    defaults: { _controller: AirSimSocialNetworkBundle:Contacts:sendFriendRequest }

# ***** Messages ***** #
air_sim_social_network_chats:
    path:     /chat_rooms
    defaults: { _controller: AirSimSocialNetworkBundle:Chat:chat }
# AJAX calls

air_sim_social_network_messages:
    path:     /chat_room/{chatId}
    defaults: { _controller: AirSimSocialNetworkBundle:ChatRoom:chatRoom }
# AJAX calls
air_sim_social_network_messages_send_message:
    path:     /messages_send_message
    defaults: { _controller: AirSimSocialNetworkBundle:ChatRoom:sendMessage }

# ***** Photo Albums ***** #
air_sim_social_network_photo_albums:
    path:     /photo_albums/{user_id}
    defaults: { _controller: AirSimSocialNetworkBundle:PhotoAlbums:photoAlbums, user_id: null }
# AJAX calls

# ***** Map ***** #
# AJAX calls
air_sim_social_network_map_get_user_marker:
    path:     /get_user_marker
    defaults: { _controller: AirSimSocialNetworkBundle:Map:getUserMarker }
air_sim_social_network_get_friends_markers:
    path:     /get_friends_markers
    defaults: { _controller: AirSimSocialNetworkBundle:Map:getFriendsMarkers }
air_sim_social_network_map_add_marker:
      path:     /map_add_marker
      defaults: { _controller: AirSimSocialNetworkBundle:Map:addMarker }

# ***** Options ***** #
air_sim_social_network_options:
    path:     /options/{type}
    defaults: { _controller: AirSimSocialNetworkBundle:Options:options }
# AJAX calls

