parameters:
#    air_sim_social_network.example.class: AirSim\Bundle\SocialNetworkBundle\Example

services:
#    air_sim_social_network.example:
#        class: %air_sim_social_network.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
